### ISSUE TITLE
how can we use this in exsisting project ?

### ISSUE THREAD

**Issue by arunxampr** [jbosse/ignite-expo-boilerplate#12]

**Comment by jbosse** [comment]
Boilerplates are for generating new applications. Are you using the Ignite CLI ? (https://github.com/infinitered/ignite)

**Comment by arunxampr** [comment]
yes, already created project using this..
now How  can I run this on expo?

**Comment by jbosse** [comment]
to run locally just type `yarn start`. To publish to Expo.io you can download their XDE that allows you to publish to their site. https://www.github.com/expo/xde/releases

**Comment by jbosse** [comment]
Did that work? Can I close this issue?
