### ISSUE TITLE
Storybook don't job

### ISSUE THREAD

**Issue by pherm** [jbosse/ignite-expo-boilerplate#14]
I have a problem when i run Storybook, @jbosse 

My steps: 
Install the app to the simulator device:
1) react-native run-ios 'iphone 6'
then i close the React Native packager.

Check storybook files:
2) getstorybook

Run storybook which host on port 7007:
3) yarn run storybook

i run RN
4)  react-native start --port=8081 

and then it return: undefined is not an object (evaluating 'RCTAsyncStorage.multiMerge'), why? 🤔

**Comment by jbosse** [comment]
I will have to look at this. Possibly Storybook is not compatible with expo? Also I don't think `react-native run-ios 'iphone 6'` is the proper way to start an Expo project. either `yarn start` or at the very least `react-native-scripts start`

**Comment by pherm** [comment]
@jbosse I don't know if expo is compatible with storybook. Ignite is compatible with storybook. In my case don't job both  yarn start or react-native-scripts start, never work. But if it doesn't job it's useless to keep storybook in this repo

**Comment by pherm** [comment]
> I will look into it when I get a chance
@jbosse uhm ok, tell me if for you work.

**Comment by dgptamayo** [comment]
Hi, I also cannot make storybook work in my ignite-expo project too.

Storybook can work with Expo: https://github.com/javidjamae/expo-with-storybook-howto

**Comment by toussa** [comment]
Hi,
It's not working for me neither. But the previous comment helped me figuring out what was happening.

To make it work, I had to do these small changes:
- Removing the line `AppRegistry.registerComponent` in ./storybook/storybook.js
- Changing ./index.js to either register the "./App/Containers/App" entrypoint or the "./storybook" entrypoint, based on a new "./App/Config/DebugConfig" variable.

Here is the code of my ./index.js:
```
import "./App/Config/ReactotronConfig";
import Expo from "expo";
import DebugConfig from "./App/Config/DebugConfig";

const entrypoint =
  __DEV__ && DebugConfig.launchStorybook
    ? require("./storybook").default
    : require("./App/Containers/App").default;

Expo.registerRootComponent(entrypoint);
```
Now, you can : 
* In one terminal, launch `yarn run storybook`
* In another one, launch `yarn run android`
* You may need to reload the app (simulator: Ctrl+m and "reload", on device: shake + "reload")

FYI, I saw that if you want hot reloading, you have to add a wrapper component of your storybookUI in ./storybook/storybook.js:
```
// react-native hot module loader must take in a Class - https://github.com/facebook/react-native/issues/10991
// https://github.com/storybooks/storybook/issues/2081
// eslint-disable-next-line react/prefer-stateless-function
class StorybookUIRoot extends Component {
  render() {
    return <StorybookUI />;
  }
}
export default StorybookUIRoot;
```

**Comment by jbosse** [comment]
@toussa do you think you would be able submit a pull request for these changes to the boilerplate?

**Comment by toussa** [comment]
@jbosse I'll try but it's unfortunately not the right timing :/ If anyone can take it, I would prefer.

BTW, Another thing that came during my development but not totally related on this issue: You might need to add a way to load fonts asynchronously with Expo in storybook => you can use the wrapper component I put in my last comment. [Here is more detail](https://docs.expo.io/versions/latest/guides/using-custom-fonts.html)

**Comment by dgptamayo** [comment]
Thanks @toussa!

Re: font loading - is it just a matter of adding something like this in a storybookUI wrapper component:

```javascript
  async componentWillMount() {
    await Expo.Font.loadAsync({
      Roboto: require('native-base/Fonts/Roboto.ttf'),
      Roboto_medium: require('native-base/Fonts/Roboto_medium.ttf'),
      Ionicons: require('@expo/vector-icons/fonts/Ionicons.ttf'),
      FontAwesome: require('@expo/vector-icons/fonts/FontAwesome.ttf'),
      CircularStdBlack: require('../Assets/CircularStd-Black.otf'),
      CircularStdBook: require('../Assets/CircularStd-Book.otf'),
      CircularStdBold: require('../Assets/CircularStd-Bold.otf'),
      CircularStdMedium: require('../Assets/CircularStd-Medium.otf'),
      CircularStdItalic: require('../Assets/CircularStd-BookItalic.otf'),
    })
    this.setState({ fontLoaded: true })
  }
```
Should this be part of the boilerplate or just as an additional information in the README.md?

**Comment by pherm** [comment]
@jbosse @dgptamayo @toussa any fix for Storybook?

**Comment by dgptamayo** [comment]
hey @pherm - i have a pending PR that's failing on integration tests, ping @jbosse

**Comment by pherm** [comment]
come on @jbosse help us to solve this issue!

**Comment by jbosse** [comment]
Sorry work has been consuming all of my mental resources. I will take a look at the PR tonight. I think it was failing some tests.

**Comment by jbosse** [comment]
I think I may have a problem with the linter. it seems to only be complaining about spaces. I wasnt able to figure it out last night. Take two tonight.

**Comment by jbosse** [comment]
Should be fixed in https://github.com/jbosse/ignite-expo-boilerplate/pull/19
