### ISSUE TITLE
update to expo sdk24/25?

### ISSUE THREAD

**Issue by Bonobomagno** [jbosse/ignite-expo-boilerplate#15]
Any plan for update?

**Comment by jbosse** [comment]
👍🏻 yes as soon as work slows down a bit.

**Comment by jbosse** [comment]
In the meantime it should just be a matter up updating your package.json if you need it.

**Comment by Bonobomagno** [comment]
also i suggest adding app.js 
just follow this [https://docs.expo.io/versions/latest/sdk/register-root-component.html](expo.io)

**Comment by Bonobomagno** [comment]
adding:
react-native-config
This is useless in expo..

**Comment by jbosse** [comment]
@Bonobomagno the ignite template uses index.js instead of app.js. The link use sent is implemented here https://github.com/jbosse/ignite-expo-boilerplate/blob/master/boilerplate/index.js.ejs#L5

**Comment by jbosse** [comment]
@Bonobomagno yes react-native-config is. I started from the ignite boilerplate and have been modifying it to get it to work with expo.

**Comment by jbosse** [comment]
Upgraded to 25 :-)
