### ISSUE TITLE
react-native-config not working with Expo

### ISSUE THREAD

**Issue by toussa** [jbosse/ignite-expo-boilerplate#20]
Hi,

I tried to use react-native-config with this boilerplate, but without success: it seems that Expo is not compatible with this module (because it uses native code). See [this expo issue](https://github.com/expo/expo/issues/83)

I suggest removing it from this boilerplate to avoid misunderstandings and update the docs

**Comment by jbosse** [comment]
I thought I removed it in this commit [https://github.com/jbosse/ignite-expo-boilerplate/commit/f8669e7678d362b2cf7cb6387fa7aa59d2f1082e] while addressing Issue #15. Is there a reference to it I forgot to remove?

**Comment by toussa** [comment]
Oh... Sorry, I didn't see the last commits you did. My bad :/ 
Thanks for your reactivity (native?:smile:)
