### ISSUE TITLE
Question: How to update to the newer version of Expo?

### ISSUE THREAD

**Issue by yudistiraAshadi** [jbosse/ignite-expo-boilerplate#28]
As written in the title, how to update to the newer or specific version of Expo SDK?

**Comment by larryrutledge** [comment]
I used this information:
https://blog.expo.io/expo-sdk-v28-0-0-is-now-available-f30e8253b530

I was able to rebuild and launch the app, though there are some javascript errors with navigation I need to resolve now. But looks like the update was successful.
