### ISSUE TITLE
Device Info section in DevScreens is not working.

### ISSUE THREAD

**Issue by deden** [jbosse/ignite-expo-boilerplate#3]
I know the DeviceInfoScreen is missing in this boilerplate.
Do you have a plan to substitute it with [Expo Constants](https://docs.expo.io/versions/latest/sdk/constants.html)?

**Comment by jbosse** [comment]
I must admit I have only been using React Native and Expo for a few weeks. I did not know about expo constants. I had to fork the DevScreens plugin to remove that section. I won't be able to get to this for a while as I am slammed at work but if you want to look at https://github.com/jbosse/ignite-dev-screens-expo to see what I yanked, you might be able to find reasonable substitutes.
