### ISSUE TITLE
I'd like to update the repository for the latest version of Expo

### ISSUE THREAD

**Issue by henrymoulton** [jbosse/ignite-expo-boilerplate#30]
As seen in #28 and #26 this package isn't aligned with the latest version of Expo (and React, React Navigation, React Navigation with Redux). 

I'd like to update the boilerplate for these packages in my fork and submit a PR. During this process I'd also like to remove the React Navigation Redux integration as this won't be supported in the upcoming release for React Navigation, see here: https://reactnavigation.org/docs/en/redux-integration.html. 

Does this sound ok?

**Comment by jbosse** [comment]
Please do! I am
Not using Expo or React At the moment and haven’t had the time.

**Comment by henrymoulton** [comment]
Cool underway

**Comment by gauravarora91** [comment]
@henrymoulton thanks, any updates on the same? Let me know if I can help for the same. Thanks!

**Comment by henrymoulton** [comment]
Found a good Sunday to do this - current commit is using Expo v30
