### ISSUE TITLE
npm run clean:android fails, unable to install native app

### ISSUE THREAD

**Issue by drdeath2609** [jbosse/ignite-expo-boilerplate#5]
I started using this boilerplate and it works perfectly fine with expo but when I ran npm run clean:android on my project it failed. So, I just created a sample app and did not change anything in the project to check whether it's something I have added as a dependency that is causing this issue. But still got the same error in Freshly created app - 

 

`
> MyLatestCreation@0.0.1 clean:android /Users/dxraider/Priyesh/projects/bittrex/MyLatestCreation
> cd android/ && ./gradlew clean && cd .. && react-native run-android

Incremental java compilation is an incubating feature.
:app:clean
:react-native-i18n:clean

BUILD SUCCESSFUL

Total time: 7.41 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html
Scanning folders for symlinks in /Users/dxraider/Priyesh/projects/bittrex/MyLatestCreation/node_modules (23ms)
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:react-native-i18n:preBuild UP-TO-DATE
:react-native-i18n:preReleaseBuild UP-TO-DATE
:react-native-i18n:checkReleaseManifest
:react-native-i18n:preDebugAndroidTestBuild UP-TO-DATE
:react-native-i18n:preDebugBuild UP-TO-DATE
:react-native-i18n:preDebugUnitTestBuild UP-TO-DATE
:react-native-i18n:preReleaseUnitTestBuild UP-TO-DATE
:react-native-i18n:prepareComAndroidSupportAppcompatV72301Library
:react-native-i18n:prepareComAndroidSupportSupportV42301Library
:react-native-i18n:prepareComFacebookFrescoDrawee061Library
:react-native-i18n:prepareComFacebookFrescoFbcore061Library
:react-native-i18n:prepareComFacebookFrescoFresco061Library
:react-native-i18n:prepareComFacebookFrescoImagepipeline061Library
:react-native-i18n:prepareComFacebookFrescoImagepipelineOkhttp061Library
:react-native-i18n:prepareComFacebookReactReactNative0120Library
:react-native-i18n:prepareOrgWebkitAndroidJscR174650Library
:react-native-i18n:prepareReleaseDependencies
:react-native-i18n:compileReleaseAidl
:react-native-i18n:compileReleaseNdk UP-TO-DATE
:react-native-i18n:compileLint
:react-native-i18n:copyReleaseLint UP-TO-DATE
:react-native-i18n:compileReleaseRenderscript
:react-native-i18n:generateReleaseBuildConfig
:react-native-i18n:generateReleaseResValues
:react-native-i18n:generateReleaseResources
:react-native-i18n:mergeReleaseResources
:react-native-i18n:processReleaseManifest
:react-native-i18n:processReleaseResources
:react-native-i18n:generateReleaseSources
:react-native-i18n:incrementalReleaseJavaCompilationSafeguard
:react-native-i18n:compileReleaseJavaWithJavac
:react-native-i18n:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:react-native-i18n:extractReleaseAnnotations
:react-native-i18n:mergeReleaseShaders
:react-native-i18n:compileReleaseShaders
:react-native-i18n:generateReleaseAssets
:react-native-i18n:mergeReleaseAssets
:react-native-i18n:mergeReleaseProguardFiles
:react-native-i18n:packageReleaseRenderscript UP-TO-DATE
:react-native-i18n:packageReleaseResources
:react-native-i18n:processReleaseJavaRes UP-TO-DATE
:react-native-i18n:transformResourcesWithMergeJavaResForRelease
:react-native-i18n:transformClassesAndResourcesWithSyncLibJarsForRelease
:react-native-i18n:mergeReleaseJniLibFolders
:react-native-i18n:transformNative_libsWithMergeJniLibsForRelease
:react-native-i18n:transformNative_libsWithSyncJniLibsForRelease
:react-native-i18n:bundleRelease
:app:prepareComAndroidSupportAppcompatV72301Library
:app:prepareComAndroidSupportRecyclerviewV72301Library
:app:prepareComAndroidSupportSupportV42301Library
:app:prepareComFacebookFrescoDrawee081Library
:app:prepareComFacebookFrescoFbcore081Library
:app:prepareComFacebookFrescoFresco081Library
:app:prepareComFacebookFrescoImagepipeline081Library
:app:prepareComFacebookFrescoImagepipelineOkhttp081Library
:app:prepareComFacebookReactReactNative0201Library
:app:prepareMyLatestCreationReactNativeI18nUnspecifiedLibrary
:app:prepareOrgWebkitAndroidJscR174650Library
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:mergeDebugShaders
:app:compileDebugShaders
:app:generateDebugAssets
:app:mergeDebugAssets
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest
:app:processDebugResources
warning: string 'catalyst_debugjs' has no default translation.
warning: string 'catalyst_element_inspector' has no default translation.
warning: string 'catalyst_jsload_error' has no default translation.
warning: string 'catalyst_jsload_message' has no default translation.
warning: string 'catalyst_jsload_title' has no default translation.
warning: string 'catalyst_reloadjs' has no default translation.
warning: string 'catalyst_settings' has no default translation.
warning: string 'catalyst_settings_title' has no default translation.

:app:generateDebugSources
:app:incrementalDebugJavaCompilationSafeguard
:app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/dxraider/Priyesh/projects/bittrex/MyLatestCreation/android/app/src/main/java/com/mylatestcreation/MainApplication.java:5: error: cannot find symbol
import com.facebook.react.ReactApplication;
                         ^
  symbol:   class ReactApplication
  location: package com.facebook.react
/Users/dxraider/Priyesh/projects/bittrex/MyLatestCreation/android/app/src/main/java/com/mylatestcreation/MainApplication.java:7: error: cannot find symbol
import com.facebook.react.ReactNativeHost;
                         ^
  symbol:   class ReactNativeHost
  location: package com.facebook.react
/Users/dxraider/Priyesh/projects/bittrex/MyLatestCreation/android/app/src/main/java/com/mylatestcreation/MainApplication.java:15: error: cannot find symbol
public class MainApplication extends Application implements ReactApplication {
                                                            ^
  symbol: class ReactApplication
/Users/dxraider/Priyesh/projects/bittrex/MyLatestCreation/android/app/src/main/java/com/mylatestcreation/MainApplication.java:17: error: cannot find symbol
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
                ^
  symbol:   class ReactNativeHost
  location: class MainApplication
/Users/dxraider/Priyesh/projects/bittrex/MyLatestCreation/android/app/src/main/java/com/mylatestcreation/MainApplication.java:38: error: cannot find symbol
  public ReactNativeHost getReactNativeHost() {
         ^
  symbol:   class ReactNativeHost
  location: class MainApplication
/Users/dxraider/Priyesh/projects/bittrex/MyLatestCreation/android/app/src/main/java/com/mylatestcreation/MainApplication.java:17: error: cannot find symbol
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
                                                       ^
  symbol:   class ReactNativeHost
  location: class MainApplication
/Users/dxraider/Priyesh/projects/bittrex/MyLatestCreation/android/app/src/main/java/com/mylatestcreation/MainApplication.java:37: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/dxraider/Priyesh/projects/bittrex/MyLatestCreation/android/app/src/main/java/com/mylatestcreation/MainActivity.java:5: error: MainActivity is not abstract and does not override abstract method getPackages() in ReactActivity
public class MainActivity extends ReactActivity {
       ^
8 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 15.137 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html`

**Comment by jbosse** [comment]
@drdeath2609 it is difficult for me to work with Android on my computer. Can you please edit `package.json` line 11 to be `"clean:android": "cd android/ && ./gradlew clean && cd .. && react-native-scripts android",` and try again? The key is changing `react-native run-android` to `react-native-scripts android`. I do not think that `react-native run-android` is valid in the Expo fork.

If it works I can make the change to master and update the npm packages.

**Comment by jbosse** [comment]
I can't run android apps at the moment. Re-open if this is still a problem.
