### ISSUE TITLE
Watch not running

### ISSUE THREAD

**Issue by secretbirds** [jbosse/ignite-expo-boilerplate#7]
Running 

```
ignite new ex -b ignite-expo
cd ex
yarn start
```

And editing Launchscreen.js doesn't update the app.

Is there something I need to to get the boilerplate to watch files?

**Comment by jbosse** [comment]
Android or iPhone. When Expo launches the App to need to enable hot reload with Command+D

**Comment by jbosse** [comment]
So it worked?

**Comment by secretbirds** [comment]
It seemed to be more to do with either adding libraries or bad network coverage. I deleted the app and started again and it's working.
